edges = [
    ('Lisboa', 'Cadiz', 2, 'true','false'),
    ('Madrid', 'Lisboa', 3,'true','false'),
    ('Madrid', 'Cadiz', 3,'true','false'),
    ('Madrid', 'Pamplona', 3,'true','true'),
    ('Madrid', 'Barcelona', 2,'true','false'),
    ('Marseille', 'Pamplona', 4,'true','false'),
    ('Marseille', 'Barcelona', 4,'false','false'),
    ('Pamplona', 'Barcelona', 2,'false','true'),
    ('Pamplona', 'Brest', 4,'true','false'),
    ('Paris', 'Pamplona', 4,'true','false'),
    ('Paris', 'Marseille', 4,'false','false'),
    ('Paris', 'Brest', 3,'true','false'),
    ('Paris', 'Dieppe', 1,'true','false'),
    ('Paris', 'Zurich', 3,'false','true'),
    ('Dieppe', 'London', 2,'false','false'),
    ('Dieppe', 'Brest',2, 'true','false')
    ('London', 'Edinburgh', 4, 'true','false'),
    ('Zurich', 'Marseille', 2),
    ('Zurich', 'Venezia', 2),
    ('Marseille', 'Roma', 4),
    ('Venezia', 'Roma', 2, 'true','false'),
    ('Zurich', 'Munchen', 2),
    ('Munchen', 'Venezia', 2),
    ('Munchen', 'Frankfurt', 2, 'true','false'),
    ('Frankfurt', 'Paris', 3, 'true','false'),
    ('Frankfurt', 'Bruxelles', 2, 'true','false'),
    ('Bruxelles', 'Paris', 2, 'true','false'),
    ('Bruxelles', 'Dieppe', 2, 'true','false'),
    ('Bruxelles', 'Amsterdam', 1, 'true','false'),
    ('Amsterdam', 'London', 2,'false','false'),
    ('Amsterdam', 'Frankfurt', 2, 'true','false'),
    ('Frankfurt', 'Essen', 2, 'true','false'),
    ('Amsterdam', 'Essen', 3, 'true','false'),
    ('Munchen', 'Wien', 3, 'true','false'),
    ('Berlin', 'Wien', 3, 'true','false'),
    ('Berlin', 'Essen', 2, 'true','false'),
    ('Berlin', 'Frankfurt', 3, 'true','false'),
    ('Wien', 'Zagrab', 2,'false','false'),
    ('Zagrab', 'Venezia', 2,'false','false'),
    ('Roma', 'Brindisi', 2, 'true','false'),
    ('Roma', 'Palermo', 4,'false','false'),
    ('Brindisi', 'Palermo', 3,'false','false'),
    ('Budapest', 'Zagrab', 2, 'true','false'),
    ('Budapest', 'Wien', 1, 'true','false'),
    ('Zagrab', 'Sarajevo', 3, 'true','false'),
    ('Sarajevo', 'Athina', 4, 'true','false'),
    ('Budapest', 'Sarajevo', 3, 'true','false'),
    ('Brindisi', 'Athina', 4,'false','false'),
    ('Athina', 'Sofia', 3, 'true','false'),
    ('Sofia', 'Sarajevo', 2),
    ('Sofia', 'Constantinople', 3, 'true','false'),
    ('Athina', 'Smyrna', 2,'false','false'),
    ('Smyrna', 'Constantinople', 2),
    ('Constantinople', 'Bucuresti', 3, 'true','false'),
    ('Bucuresti', 'Sofia', 2),
    ('Bucuresti', 'Budapest', 4),
    ('Budapest', 'Kiev', 6),
    ('Bucuresti', 'Kiev', 4,'false','false'),
    ('Kiev', 'Warzawa', 4,'false','false'),
    ('Warzawa', 'Berlin', 4, 'true','false'),
    ('Warzawa', 'Wien', 4, 'true','false')
    ('Constantinople', 'Angora', 2),
    ('Smyrna', 'Angora', 3),
    ('Angora', 'Erzerum', 3, 'true','false'),
    ('Sevastopol', 'Constantinople', 4,'false','false'),
    ('Sevastopol', 'Erzerum', 4,'false','false'),
    ('Sochi', 'Erzerum', 3),
    ('Sevastopol', 'Sochi', 2,'false','false'),
    ('Sochi', 'Rostov', 2,'false','false'),
    ('Sevastopol', 'Rostov', 4,'false','false'),
    ('Rostov', 'Kharkov', 2, 'true','false'),
    ('Kharkov', 'Kiev', 4,'false','false'),
    ('Kharkov', 'Moskva', 4,'false','false'),
    ('Sevastopol', 'Bucuresti', 4, 'true','false'),
    ('Moskva', 'Smolensk', 2, 'true','false'),
    ('Moskva', 'Petrograd', 4, 'true','false'),
    ('Petrograd', 'Wilno', 4, 'true','false'),
    ('Petrograd', 'Riga', 4,'false','false'),
    ('Petrograd', 'Stockholm', 8),
    ('Stockholm', 'Khobenhaven', 3,'true','false'),
    ('Khobenhaven', 'Essen', 3,'false','false'),
    ('Riga', 'Danzig', 3, 'true','false'),
    ('Danzig', 'Berlin', 3,'false','false'),
    ('Danzig', 'Warzawa', 2,'false','false'),
    ('Warzawa', 'Wilno', 3, 'true','false'),
    ('Wilno', 'Riga', 4), 'true','false',
    ('Wilno', 'Smolensk', 3, 'true','false'),
    ('Wilno', 'Kiev', 2),
    ('Smolensk', 'Kiev', 3, 'true','false')
]
import csv

with open('edges.csv', 'w', newline='') as csvfile:
    edge_writer = csv.writer(csvfile)
    edge_writer.writerow(['Source', 'Target', 'Weight'])
    edge_writer.writerows(edges)